version: '2'
services:
  app:
    build: .
    image: aikiio/pets
    container_name: pets_app_1
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/pets
    links:
      - db:mongodb
    depends_on:
      - db

  db:
    image: mongo:3.6
    container_name: pets_db_1
  